services:
  # Our replicated query apis
  query_api:
    build:
      dockerfile: query_api.dockerfile
    #ports:
    #  - "8080/tcp"
    volumes:
        - /var/transferware.ai-main/python_src/scratch:/python_src/scratch #TODO match with your system
    user: root #temporary
    environment:
      - "TRANSFERWARE_QUERY.TORCH_DEVICE=cpu" # TODO with the nvidia runtime this can be cuda
    deploy:
      replicas: 2
    depends_on:
      - balancer
      - broker
    labels:
      - "traefik.enable=true"
      # Entry point HTTPS
      - "traefik.http.routers.query-api.entrypoints=websecure"
      # Enable TLS
      - "traefik.http.routers.query-api.tls=true"
      - "traefik.http.routers.query-api.tls.certresolver=default"
      # Strip /api as the python server serves on root
      - "traefik.http.middlewares.strip-api.stripprefix.prefixes=/api"
      # Namespace query api on /api to allow static site on root
      - "traefik.http.routers.query-api.rule=Host('transferware-ai.umd.umich.edu') && PathPrefix(`/api`)"
      - "traefik.http.routers.query-api.middlewares=strip-api"
      - "traefik.http.services.query-api.loadbalancer.server.port=8000"

  # Serves the frontend
  static_site:
    build:
      dockerfile: static_site.dockerfile
    #ports:
    #  - "8080/tcp"
    deploy:
      replicas: 2
    depends_on:
      - balancer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static-site.rule=Host('transferware-ai.umd.umich.edu') && PathPrefix(`/`) && !PathPrefix(`/api`)"
      - "traefik.http.routers.static-site.entrypoints=websecure"
      - "traefik.http.routers.static-site.tls=true"
      - "traefik.http.routers.static-site.tls.certresolver=default"
  # MQTT broker
  broker:
    hostname: broker
    image: eclipse-mosquitto
    ports:
      - "1883"
    volumes:
      - /var/transferware.ai-main/mosquitto.conf:/mosquitto/config/mosquitto.conf
    user: root #temporary
    depends_on:
      - balancer
    labels:
      - "traefik.enable=false"

  # Reverse proxy
  balancer:
    image: traefik
    ports:
      # Our application
      - "80:80"
      # HTTPS support
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - /var/transferware.ai-main/traefik.yml:/etc/traefik/traefik.yml
      - /run/podman/podman.sock:/var/run/docker.sock
      - /var/transferware.ai-main/cert.crt:/etc/traefik/cert.crt
      - /var/transferware.ai-main/cert.key:/etc/traefik/cert.key
    user: root #temporary