# Docker configuration backend
providers:
  docker:
    {}
  file:
    filename: /etc/traefik/tls.yml

entryPoints:
  # Redirect HTTP to HTTPS
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http:
      tls: {}

  dashboard:
    address: ":8081"

#tls:
#  stores: 
#    default:
#      defaultCertificate:
#        certFile: "/etc/letsencrypt/live/transferware-ai.umd.umich.edu/fullchain.pem"
#        keyFile: "/etc/letsencrypt/live/transferware-ai.umd.umich.edu/privkey.pem"

# API and dashboard configuration
api:
  dashboard: true
  insecure: true

log:
  level: DEBUG
