# Docker configuration backend
providers:
  docker:
    { }
    
entryPoints:
  #Redirect HTTP to HTTPS
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

tls:
  certificates:
    - certFile: "/etc/traefik/fullchain.pem"
      keyFile: "/etc/traefik/privkey.pem"

  options:
    default:
      minVersion: "TLSv1.2"

  stores:
    default:
      defaultCertificate:
        certFile: "/etc/traefik/fullchain.pem"
        keyFile: "/etc/traefik/privkey.pem"

# API and dashboard configuration
api:
  insecure: true