# Docker configuration backend
providers:
  docker:
    { }
    
entryPoints:
  #Redirect HTTP to HTTPS
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

tls:
  certificates: 
    - certFile: "/etc/letsencrypt/live/transferware-ai.umd.umich.edu/fullchain.pem"
      keyFile: "/etc/letsencrypt/live/transferware-ai.umd.umich.edu/privkey.pem"
      
# API and dashboard configuration
api:
  insecure: true