# Default settings file

# Abstract factory used
model_implimentation = "ZhaoModelFactory"
# Changes wether the cache will be automatically updated. Use for debugging
update_cache = true
# Token used for controling access to query api
access_token = "CHANGE ME" # TODO change for prod

# Settings for the training script
[training]
torch_device = "cuda"
# Num epochs to train
epochs = 30
# Number of epochs val loss worsens before we early stop
early_stopping_thresh = 3
# Num images loaded per step in epoch
batch_size = 9
# The directory the cache and model resources will be written to
resource_dir = "../scratch" # TODO change for prod
# Validation directory. Should contain folders of pattern ids with images in them.
validation_dir = "../scratch/val" # TODO change for prod
# URL to connect to API for upadates
api_url = "http://0.0.0.0:8080"
# IDs to skip when training the model. Use when training errors due to corrupted image files.
skip_ids = [67001]
# Least acceptible validation percent that will still deploy the model
validation_threshold = 0.7 # TODO change for prod
# Updates index only when updating, rather than retraining the model entirely
update_index_only = false

# Settings for the query api
[query]
torch_device = "cuda"
# The directory the cache and model resources will be read from, and written to on update
resource_dir = "../scratch" # TODO change for prod
# Number of results to get from the model
top_k = 10
# Server settings
host = "0.0.0.0"
port = 8080
# Number of server processes to spawn. Each will load the model, so watch VRAM. Allows for horizontal scaling.
workers = 1
# IDs to skip when training the model. Use when training errors due to corrupted image files.
skip_ids = [67001]
# CORS origins to allow
origins = ["*"]